server:
  port: 8085
spring:
  datasource:
    username: lameute
    url: jdbc:postgresql://localhost:5433/account_db
    password: lameutepass
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'

twilio:
  account_sid: ACf90a1b3400c4f710647d397191a01334
  auth_token: 462a32dd14a59d320811b4770e67e3ce
  service_id: VA379fa37df7250ef621b10b981359e3ec

secret:
  signing_key: An23aU8bnGb3TzHx22ybf4tEA5jRBRf1VxJ0InUdBg6lGgkvmLKsKVDUpRsmZEXQ
