server:
  port: 8085
spring:
  datasource:
    username: lameute
    url: jdbc:postgresql://localhost:5433/account_db
    password: lameutepass
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: create-drop
    show-sql: 'true'

twilio:
  account_sid: ACf90a1b3400c4f710647d397191a01334
  auth_token: ca8a00f0bb17df61eb60033b9feb56d0
  service_id: VA14242fe0dab02f584e95fca3a4c2df8b