server:
  port: 8085
spring:
  datasource:
    username: lameute
    url: jdbc:postgresql://localhost:5433/account_db
    password: lameutepass
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'

springdoc:
  api-docs:
    path: /doc/account-service/v3/api-docs
  swagger-ui:
    path: /doc/account-service/swagger-ui/index.html

twilio:
  account_sid: ${TWILIO_ACCOUNT_SID}
  auth_token: ${TWILIO_AUTH_TOKEN}
  service_id: ${TWILIO_SERVICE_ID}

secret:
  signing_key: An23aU8bnGb3TzHx22ybf4tEA5jRBRf1VxJ0InUdBg6lGgkvmLKsKVDUpRsmZEXQ
