server:
  port: 8089
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: account-service
          uri: lb:http://ACCOUNT-SERVICE
          predicates:
            - Path=/users/** , /doc/account-service/**
        - id: ride-service
          uri: lb:http://RIDE-SERVICE
          predicates:
            - Path=/rides/** , /doc/ride-service/**
        - id: reservation-service
          uri: lb:http://RESERVATION-SERVICE
          predicates:
            - Path=/reservations/** , /doc/reservation-service/**
        - id: expedition-service
          uri: lb:http://EXPEDITION-SERVICE
          predicates:
            - Path=/expeditions/** , /doc/expedition-service/**
        - id: chat-service-websocket
          uri: lb:ws://CHAT-SERVICE
          predicates:
            - Path=/ws/**, /doc/chat-service/**

  datasource:
    username: lameute
    url: jdbc:postgresql://localhost:5433/account_db
    password: lameutepass
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'
  main:
    web-application-type: reactive

springdoc:
  api-docs:
    path: /doc/api-gateway/v3/api-docs
  swagger-ui:
    path: /doc/api-gateway/swagger-ui/index.html
    urls:
      - url: /doc/api-gateway/v3/api-docs
        name: API Gateway Service
      - url: /doc/account-service/v3/api-docs
        name: Account Service

secret:
  signing_key: An23aU8bnGb3TzHx22ybf4tEA5jRBRf1VxJ0InUdBg6lGgkvmLKsKVDUpRsmZEXQ