server:
  port: 8083
spring:
  data:
    mongodb:
      username: lameute
      password: lameutepass
      host: localhost
      port: 27017
      database: notification_db
      authentication-database: admin
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: rideId
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: RideInfo:com.lameute.notification_service.kafka.RideInfo

#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: let
#    password: sawd ydew uqqg tvpc
#    smtp:
#      auth: true
#      starttls:
#        enable: true