server:
  port: 8087
spring:
  datasource:
    username: lameute
    url: jdbc:postgresql://localhost:5438/reservation_db
    password: lameutepass
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'

application:
  config:
    account-url: http://localhost:8085/users
    ride-url: http://localhost:8086/rides

upload:
  path: vehicle-images