server:
  port: 8086
spring:
  datasource:
    username: lameute
    url: jdbc:postgresql://localhost:5434/ride_db
    password: lameutepass
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: create-drop
    show-sql: 'true'