server:
  port: 8086
spring:
  datasource:
    username: lameute
    url: jdbc:postgresql://localhost:5437/ride_db
    password: lameutepass
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: PassengerList:com.lameute.ride_service.kafka.PassengerList

application:
  config:
    account-url: http://localhost:8085/users
    reservation-url: http://localhost:8087/reservations

upload:
  path: vehicle-images